version: "3.8"
services:
  db:
    image: postgres:15.4-alpine3.18
    env_file: ../postgres/.env
    ports:
      - 5432:5432
  web:
    image: roadprimus/my_crud:v0.0.2
    env_file: .env
    ports:
      - 80:8000
    depends_on:
      - db
    links:
      - db:db