apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pg.secret.name }}
  namespace: {{ .Values.namespace.name }}
stringData:
  POSTGRES_DB: my_db
  POSTGRES_HOST: db
  POSTGRES_PASSWORD: my_password
  POSTGRES_USER: my_user
  POSTGRES_PORT: "5432"